version: '3.3'

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - static_volume:/home/eletrader/web/staticfiles
      - media_volume:/home/eletrader/web/mediafiles
  web:
    build: ./eletrader
    command: bash -c "python3 manage.py migrate --settings eletrader.settings.pro && gunicorn --env DJANGO_SETTINGS_MODULE=eletrader.settings.pro eletrader.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    depends_on:
      - db
    volumes:
      - static_volume:/home/eletrader/web/staticfiles
      - media_volume:/home/eletrader/web/mediafiles
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=eletrader_user
      - POSTGRES_PASSWORD=eletrader_password
      - POSTGRES_DB=eletrader

volumes:
  postgres_data:
  static_volume:
  media_volume:
