version: '3.3'

services:
  web:
    build: ./eletrader
    command: bash -c "python3 manage.py runserver 0.0.0.0:8000 --settings eletrader.settings.pro  && python3 manage.py migrate --settings eletrader.settings.pro"
    volumes:
      - ./eletrader/:/home/szymon/eletrader/
    ports:
      - 8000:8000
        #env_file:
        #- ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=eletrader_user
      - POSTGRES_PASSWORD=eletrader_password
      - POSTGRES_DB=eletrader

volumes:
  postgres_data:
