version: '3.3'

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - static_volume:/home/eletrader/web/staticfiles
      - media_volume:/home/eletrader/web/mediafiles
  web:
    build: ./eletrader
    expose:
      - 8000
    depends_on:
      - db
    volumes:
      - static_volume:/home/eletrader/web/staticfiles
      - media_volume:/home/eletrader/web/mediafiles
  db:
    build: ./postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgresql/backups:/backups
    environment:
      - POSTGRES_USER=eletrader_user
      - POSTGRES_PASSWORD=eletrader_password
      - POSTGRES_DB=eletrader
      - BACKUP_LIVING_MONTHS=6

volumes:
  postgres_data:
  static_volume:
  media_volume:
